"""remove name null constraint

Revision ID: 74921986a8df
Revises: 6ca6cdcf1416
Create Date: 2026-07-26 01:15:13.797056

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74921986a8df"
down_revision = "6ca6cdcf1416"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as tb:
        tb.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as tb:
        tb.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
